/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import psipacientes.motor;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class principalView extends javax.swing.JFrame {

    public void showTableData(ResultSet rs) {
        try {

            familiaTable.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);

        }

    }

    public void setDatos() {
        id = m.getId();

        try {
            java.util.Date date = new SimpleDateFormat("dd/MM/yyyy").parse(m.getNacimiento(id));
            dateText.setDate(date);
        } catch (ParseException ex) {
            Logger.getLogger(principalView.class.getName()).log(Level.SEVERE, null, ex);
        }
        nameText.setText(m.getNombre(id));
        apellidoText.setText(m.getApellido(id));
        edadText.setValue(m.getEdad(id));
        lvlText.setSelectedItem(m.getLvl(id));
        religionText.setSelectedItem(m.getReligion(id));
        ocupacionText.setText(m.getOcupacion(id));
        actText.setText(m.getAct(id));
        direccionText.setText(m.getDireccion(id));
        telefonoText.setText(m.getTelefono(id));
        asuntoText.setText(m.getAsunto(id));
        objText.setText(m.getObjetivo(id));
        fechaIngreso.setText(m.getIngreso(id));
        //===========================
        evolucionText.setText(m.getEvolucion(id));
        causasText.setText(m.getCausas(id));
        accionesText.setText(m.getAcciones(id));
        implicacionesText.setText(m.getImplicaciones(id));
        //===========================================
        socialText.setText(m.getSocial(id));
        laboralText.setText(m.getLaboral(id));
        viviendaText.setText(m.getVivienda(id));
        //===========================================
        antSexualText.setText(m.getAbuso(id));
        embarazoEdad.setValue(m.getEdadSexual(id));
        preferenciaText.setText(m.getPref(id));
        
        if (m.getEmbarazo(id).equals("Si")) {
            siEmbarazo.setSelected(true);
            
        } else if (m.getEmbarazo(id).equals("No")) {
            noEmbarazo.setSelected(true);
            embarazoEdad.setEnabled(false);
        } else {
            siEmbarazo.setSelected(false);
            noEmbarazo.setSelected(false);
        }
        if (m.getTraumas(id).equals("Si")) {
            siTrauma.setSelected(true);

        } else if (m.getTraumas(id).equals("No")) {
            noTrauma.setSelected(true);
            infoTraumaText.setEnabled(false);

        } else {
            siTrauma.setSelected(false);
            noTrauma.setSelected(false);
        }
        infoTraumaText.setText(m.getInfoTraumas(id));
        //==========================================
        dreamText.setText(m.getDream(id));
        alimentoText.setText(m.getAlimenticio(id));
        antPsiText.setText(m.getAntPsicologicos(id));
        //=============================================
        enfermedadText.setText(m.getGrave(id));
        accidenteText.setText(m.getAccidentes(id));
        medicamentoText.setText(m.getMedicamento(id));
        intervencionText.setText(m.getQuirurgica(id));
        auxText.setText(m.getAuxiliar(id));
        //============================================
        antFamPsiText.setText(m.getPsicologia(id));
        antFamPsiqText.setText(m.getPsiquiatra(id));
        antFamPatText.setText(m.getPatologia(id));
        //==============================================
        lenguajeText.setText(m.getLenguaje(id));
        emocionalText.setText(m.getEmocional(id));
        realidadText.setText(m.getRealidad(id));
        higieneText.setText(m.getHigiene(id));
        //==============================================
        diagnosticoText.setText(m.getDiagnostico(id));
        observacionText.setText(m.getObservaciones(id));
        //==============================================
        showTableData(m.getFamiliaress(id));

    }

    public void setMotor(motor m) {
        this.m = m;
    }

    /**
     * Creates new form principalView
     */
    public principalView() {
        initComponents();

        fechaIngreso.enable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        apellidoText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        edadText = new javax.swing.JSpinner();
        dateText = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lvlText = new javax.swing.JComboBox<>();
        religionText = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ocupacionText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        actText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        direccionText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        telefonoText = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        asuntoText = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        objText = new javax.swing.JTextField();
        volver = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        jLabel48 = new javax.swing.JLabel();
        fechaIngreso = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        evolucionText = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        accionesText = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        causasText = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        implicacionesText = new javax.swing.JTextArea();
        VolverProblema = new javax.swing.JButton();
        EditarProblema = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        socialText = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        laboralText = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        viviendaText = new javax.swing.JTextArea();
        editarSociales = new javax.swing.JButton();
        volverSocial = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        embarazoEdad = new javax.swing.JSpinner();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        preferenciaText = new javax.swing.JTextField();
        siEmbarazo = new javax.swing.JRadioButton();
        noEmbarazo = new javax.swing.JRadioButton();
        siTrauma = new javax.swing.JRadioButton();
        noTrauma = new javax.swing.JRadioButton();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        infoTraumaText = new javax.swing.JTextArea();
        jScrollPane27 = new javax.swing.JScrollPane();
        antSexualText = new javax.swing.JTextArea();
        editarSexual = new javax.swing.JButton();
        volverSexual = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        dreamText = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        alimentoText = new javax.swing.JTextArea();
        jScrollPane12 = new javax.swing.JScrollPane();
        antPsiText = new javax.swing.JTextArea();
        editarHabitos = new javax.swing.JButton();
        volverHabito = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        enfermedadText = new javax.swing.JTextArea();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane14 = new javax.swing.JScrollPane();
        accidenteText = new javax.swing.JTextArea();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane15 = new javax.swing.JScrollPane();
        medicamentoText = new javax.swing.JTextArea();
        jLabel32 = new javax.swing.JLabel();
        jScrollPane16 = new javax.swing.JScrollPane();
        intervencionText = new javax.swing.JTextArea();
        jLabel33 = new javax.swing.JLabel();
        jScrollPane17 = new javax.swing.JScrollPane();
        auxText = new javax.swing.JTextArea();
        editarClinico = new javax.swing.JButton();
        volverClinico = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jScrollPane18 = new javax.swing.JScrollPane();
        antFamPsiText = new javax.swing.JTextArea();
        jLabel35 = new javax.swing.JLabel();
        jScrollPane19 = new javax.swing.JScrollPane();
        antFamPsiqText = new javax.swing.JTextArea();
        jLabel36 = new javax.swing.JLabel();
        jScrollPane20 = new javax.swing.JScrollPane();
        antFamPatText = new javax.swing.JTextArea();
        editarAntFam = new javax.swing.JButton();
        VolverAntFam = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jScrollPane21 = new javax.swing.JScrollPane();
        lenguajeText = new javax.swing.JTextArea();
        jLabel38 = new javax.swing.JLabel();
        jScrollPane22 = new javax.swing.JScrollPane();
        emocionalText = new javax.swing.JTextArea();
        jLabel39 = new javax.swing.JLabel();
        jScrollPane23 = new javax.swing.JScrollPane();
        realidadText = new javax.swing.JTextArea();
        jLabel40 = new javax.swing.JLabel();
        jScrollPane24 = new javax.swing.JScrollPane();
        higieneText = new javax.swing.JTextArea();
        editarMental = new javax.swing.JButton();
        volverMental = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jScrollPane25 = new javax.swing.JScrollPane();
        diagnosticoText = new javax.swing.JTextArea();
        jLabel42 = new javax.swing.JLabel();
        jScrollPane26 = new javax.swing.JScrollPane();
        observacionText = new javax.swing.JTextArea();
        editarReporte = new javax.swing.JButton();
        volverReporte = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        familiaTable = new javax.swing.JTable();
        volverFam = new javax.swing.JButton();
        ingresarFamiliar = new javax.swing.JButton();
        borrar = new javax.swing.JButton();
        jLabel43 = new javax.swing.JLabel();
        famNombre = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        famParentesco = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        famOcupacion = new javax.swing.JTextField();
        famEdad = new javax.swing.JSpinner();
        jLabel47 = new javax.swing.JLabel();
        famApellido = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellido");

        jLabel3.setText("Edad");

        jLabel4.setText("Nacimiento");

        jLabel5.setText("Escolaridad");

        lvlText.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguno", "Primaria", "Secundaria", "Bachillerato", "Profesional", "Licenciatura", "Posgrado", "Doctorado" }));

        religionText.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cristiano", "Catolico", "Judio", "Otro" }));

        jLabel6.setText("Religion");

        jLabel7.setText("Ocupacion");

        jLabel8.setText("Actividad Extra");

        jLabel9.setText("Direccion");

        direccionText.setToolTipText("");

        jLabel10.setText("Telefono");

        jLabel11.setText("Asunto o Motivo de la consulta");

        jLabel12.setText("Objetivo Terapeutico");

        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        editar.setText("Editar Datos");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });

        jLabel48.setText("Fecha de ingreso");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(dateText, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lvlText, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(religionText, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(edadText, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(nameText)
                        .addComponent(apellidoText, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)))
                .addGap(97, 97, 97)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(editar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 829, Short.MAX_VALUE)
                        .addComponent(volver))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(ocupacionText, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(actText, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(direccionText, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(telefonoText, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(asuntoText, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(objText, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(102, 102, 102)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel48)
                                    .addComponent(fechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7)
                            .addComponent(jLabel48))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ocupacionText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(apellidoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(actText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(direccionText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edadText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addComponent(telefonoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lvlText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(asuntoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(religionText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(objText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(editar)
                        .addContainerGap(380, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volver)
                        .addContainerGap())))
        );

        jTabbedPane1.addTab("Informacion General", jPanel1);

        jLabel13.setText("Evolucion");

        jLabel14.setText("Acciones realizadas en busca de solucion");

        jLabel15.setText("Causas");

        jLabel16.setText("Implicaciones (a nivel familiar, social, academico, etc.)");

        evolucionText.setColumns(20);
        evolucionText.setRows(5);
        jScrollPane1.setViewportView(evolucionText);

        accionesText.setColumns(20);
        accionesText.setRows(5);
        jScrollPane2.setViewportView(accionesText);

        causasText.setColumns(20);
        causasText.setRows(5);
        jScrollPane3.setViewportView(causasText);

        implicacionesText.setColumns(20);
        implicacionesText.setRows(5);
        jScrollPane4.setViewportView(implicacionesText);

        VolverProblema.setText("Volver");
        VolverProblema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverProblemaActionPerformed(evt);
            }
        });

        EditarProblema.setText("Editar Datos");
        EditarProblema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarProblemaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(VolverProblema))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16)
                            .addComponent(EditarProblema)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1045, Short.MAX_VALUE)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane4))
                        .addGap(0, 230, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EditarProblema)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 243, Short.MAX_VALUE)
                .addComponent(VolverProblema)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Definicion del problema", jPanel2);

        jLabel17.setText("Entorno Social");

        jLabel18.setText("Entorno Laboral");

        jLabel19.setText("Entorno de Vivienda");

        socialText.setColumns(20);
        socialText.setRows(5);
        jScrollPane6.setViewportView(socialText);

        laboralText.setColumns(20);
        laboralText.setRows(5);
        jScrollPane7.setViewportView(laboralText);

        viviendaText.setColumns(20);
        viviendaText.setRows(5);
        jScrollPane8.setViewportView(viviendaText);

        editarSociales.setText("Guardar Datos");
        editarSociales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarSocialesActionPerformed(evt);
            }
        });

        volverSocial.setText("Volver");
        volverSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverSocialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editarSociales)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 1045, Short.MAX_VALUE)
                    .addComponent(jScrollPane7)
                    .addComponent(jScrollPane8))
                .addContainerGap(212, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(volverSocial)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editarSociales)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 380, Short.MAX_VALUE)
                .addComponent(volverSocial)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Exploracion de redes sociales", jPanel4);

        jLabel20.setText("Antecedentes de abuso sexual");

        jLabel21.setText("Embarazos");

        jLabel22.setText("A que edad?");

        jLabel23.setText("Preferencia Sexual");

        jLabel24.setText("Exposicion a eventos traumaticos en esta area?");

        siEmbarazo.setText("Si");
        siEmbarazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siEmbarazoActionPerformed(evt);
            }
        });

        noEmbarazo.setText("No");
        noEmbarazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noEmbarazoActionPerformed(evt);
            }
        });

        siTrauma.setText("Si");
        siTrauma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siTraumaActionPerformed(evt);
            }
        });

        noTrauma.setText("No");
        noTrauma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noTraumaActionPerformed(evt);
            }
        });

        jLabel26.setText("Cuales?");

        infoTraumaText.setColumns(20);
        infoTraumaText.setRows(5);
        jScrollPane9.setViewportView(infoTraumaText);

        antSexualText.setColumns(20);
        antSexualText.setRows(5);
        jScrollPane27.setViewportView(antSexualText);

        editarSexual.setText("Guardar Datos");
        editarSexual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarSexualActionPerformed(evt);
            }
        });

        volverSexual.setText("Volver");
        volverSexual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverSexualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel24)
                            .addComponent(siEmbarazo)
                            .addComponent(noEmbarazo)
                            .addComponent(noTrauma)
                            .addComponent(siTrauma)
                            .addComponent(jLabel26)
                            .addComponent(jLabel20)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(preferenciaText, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(embarazoEdad, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane27, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addComponent(editarSexual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 492, Short.MAX_VALUE)
                        .addComponent(volverSexual)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(siEmbarazo)
                .addGap(18, 18, 18)
                .addComponent(noEmbarazo)
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addComponent(embarazoEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addComponent(preferenciaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel24)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(siTrauma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(noTrauma)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel26)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(editarSexual)
                        .addComponent(volverSexual)))
                .addContainerGap(240, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Historia sexual", jPanel5);

        jLabel25.setText("Hábitos de sueño");

        jLabel27.setText("Hábitos alimenticios");

        jLabel28.setText("Antecedentes psicológicos paciente");

        dreamText.setColumns(20);
        dreamText.setRows(5);
        jScrollPane10.setViewportView(dreamText);

        alimentoText.setColumns(20);
        alimentoText.setRows(5);
        jScrollPane11.setViewportView(alimentoText);

        antPsiText.setColumns(20);
        antPsiText.setRows(5);
        jScrollPane12.setViewportView(antPsiText);

        editarHabitos.setText("Guardar Datos");
        editarHabitos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarHabitosActionPerformed(evt);
            }
        });

        volverHabito.setText("Volver");
        volverHabito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverHabitoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editarHabitos)
                    .addComponent(jLabel28)
                    .addComponent(jLabel27)
                    .addComponent(jLabel25)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 1041, Short.MAX_VALUE)
                    .addComponent(jScrollPane11)
                    .addComponent(jScrollPane12))
                .addContainerGap(229, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(volverHabito)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel25)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel27)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jLabel28)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editarHabitos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 333, Short.MAX_VALUE)
                .addComponent(volverHabito)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Habitos", jPanel6);

        jLabel29.setText("¿Ha tenido alguna enfermedad grave?");

        enfermedadText.setColumns(20);
        enfermedadText.setRows(5);
        jScrollPane13.setViewportView(enfermedadText);

        jLabel30.setText("Accidentes/lesiones");

        accidenteText.setColumns(20);
        accidenteText.setRows(5);
        jScrollPane14.setViewportView(accidenteText);

        jLabel31.setText("¿Utiliza algún medicamento?");

        medicamentoText.setColumns(20);
        medicamentoText.setRows(5);
        jScrollPane15.setViewportView(medicamentoText);

        jLabel32.setText("Intervención quirúrgica");

        intervencionText.setColumns(20);
        intervencionText.setRows(5);
        jScrollPane16.setViewportView(intervencionText);

        jLabel33.setText("Utiliza lentes u otro dispositivo auxiliar");

        auxText.setColumns(20);
        auxText.setRows(5);
        jScrollPane17.setViewportView(auxText);

        editarClinico.setText("Guardar Datos");
        editarClinico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarClinicoActionPerformed(evt);
            }
        });

        volverClinico.setText("Volver");
        volverClinico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverClinicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel33)
                        .addGap(379, 379, 379))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(volverClinico))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane14, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
                            .addComponent(jScrollPane13)
                            .addComponent(jScrollPane15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(editarClinico))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32)
                            .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel33))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel31)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel32)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(editarClinico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 237, Short.MAX_VALUE)
                .addComponent(volverClinico)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Antecedentes clinicos", jPanel7);

        jLabel34.setText("Área psicológica");

        antFamPsiText.setColumns(20);
        antFamPsiText.setRows(5);
        jScrollPane18.setViewportView(antFamPsiText);

        jLabel35.setText("Área psiquiátrica");

        antFamPsiqText.setColumns(20);
        antFamPsiqText.setRows(5);
        jScrollPane19.setViewportView(antFamPsiqText);

        jLabel36.setText("Otras patologías");

        antFamPatText.setColumns(20);
        antFamPatText.setRows(5);
        jScrollPane20.setViewportView(antFamPatText);

        editarAntFam.setText("Guardar  Datos");
        editarAntFam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarAntFamActionPerformed(evt);
            }
        });

        VolverAntFam.setText("Volver");
        VolverAntFam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverAntFamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editarAntFam)
                    .addComponent(jLabel36)
                    .addComponent(jLabel35)
                    .addComponent(jLabel34)
                    .addComponent(jScrollPane18, javax.swing.GroupLayout.DEFAULT_SIZE, 1053, Short.MAX_VALUE)
                    .addComponent(jScrollPane19)
                    .addComponent(jScrollPane20))
                .addContainerGap(217, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(VolverAntFam)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel34)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel35)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel36)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editarAntFam)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 386, Short.MAX_VALUE)
                .addComponent(VolverAntFam)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Antecedentes familiares", jPanel8);

        jLabel37.setText("PERCEPCION Y LENGUAJE");

        lenguajeText.setColumns(20);
        lenguajeText.setRows(5);
        jScrollPane21.setViewportView(lenguajeText);

        jLabel38.setText("ESTADO EMOCIONAL");

        emocionalText.setColumns(20);
        emocionalText.setRows(5);
        jScrollPane22.setViewportView(emocionalText);

        jLabel39.setText("CONTACTO CON LA REALIDAD");

        realidadText.setColumns(20);
        realidadText.setRows(5);
        jScrollPane23.setViewportView(realidadText);

        jLabel40.setText("HIGIENE Y APARIENCIA PERSONAL");

        higieneText.setColumns(20);
        higieneText.setRows(5);
        jScrollPane24.setViewportView(higieneText);

        editarMental.setText("Guardar Datos");
        editarMental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarMentalActionPerformed(evt);
            }
        });

        volverMental.setText("Volver");
        volverMental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverMentalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel37)
                    .addComponent(jLabel38)
                    .addComponent(jLabel39)
                    .addComponent(jLabel40)
                    .addComponent(editarMental)
                    .addComponent(jScrollPane21, javax.swing.GroupLayout.DEFAULT_SIZE, 1061, Short.MAX_VALUE)
                    .addComponent(jScrollPane22)
                    .addComponent(jScrollPane23)
                    .addComponent(jScrollPane24))
                .addContainerGap(220, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(volverMental)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel37)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel38)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel39)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel40)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editarMental)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 246, Short.MAX_VALUE)
                .addComponent(volverMental)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Analisis del estado mental", jPanel9);

        jLabel41.setText("IMPRESIÓN DIAGNÓSTICA");

        diagnosticoText.setColumns(20);
        diagnosticoText.setRows(5);
        jScrollPane25.setViewportView(diagnosticoText);

        jLabel42.setText("OBSERVACIONES GENERALES");

        observacionText.setColumns(20);
        observacionText.setRows(5);
        jScrollPane26.setViewportView(observacionText);

        editarReporte.setText("Guardar Datos");
        editarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarReporteActionPerformed(evt);
            }
        });

        volverReporte.setText("Volver");
        volverReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel41)
                            .addComponent(jLabel42)
                            .addComponent(jScrollPane25, javax.swing.GroupLayout.DEFAULT_SIZE, 1063, Short.MAX_VALUE)
                            .addComponent(jScrollPane26))
                        .addGap(0, 212, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(editarReporte)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volverReporte)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel41)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane25, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel42)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(volverReporte))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane26, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(editarReporte)
                        .addGap(27, 27, 27)))
                .addGap(241, 241, 241))
        );

        jTabbedPane1.addTab("Reporte de sesion", jPanel10);

        familiaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        familiaTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                familiaTableMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(familiaTable);

        volverFam.setText("Volver");
        volverFam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverFamActionPerformed(evt);
            }
        });

        ingresarFamiliar.setText("Ingresar Datos");
        ingresarFamiliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarFamiliarActionPerformed(evt);
            }
        });

        borrar.setText("Borrar Datos");
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });

        jLabel43.setText("Nombre");

        famNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                famNombreActionPerformed(evt);
            }
        });

        jLabel44.setText("Parentesco");

        jLabel45.setText("Edad");

        jLabel46.setText("Ocupacion");

        jLabel47.setText("Apellido");

        famApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                famApellidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 1047, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(borrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(volverFam))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel43)
                            .addComponent(jLabel44)
                            .addComponent(jLabel45)
                            .addComponent(jLabel46)
                            .addComponent(famEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(famNombre)
                            .addComponent(famParentesco)
                            .addComponent(famOcupacion, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addComponent(ingresarFamiliar)
                            .addComponent(jLabel47)
                            .addComponent(famApellido))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 882, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel43)
                .addGap(18, 18, 18)
                .addComponent(famNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel47)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(famApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel44)
                .addGap(18, 18, 18)
                .addComponent(famParentesco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel45)
                .addGap(18, 18, 18)
                .addComponent(famEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel46)
                .addGap(18, 18, 18)
                .addComponent(famOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ingresarFamiliar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volverFam)
                    .addComponent(borrar))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Estructura y funcionalidad familiar", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        // TODO add your handling code here:
        m.openPacientes();
        m.closePrincipal();
    }//GEN-LAST:event_volverActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        // TODO add your handling code here:
  if (dateText.getDate() == null) {
            JOptionPane.showMessageDialog(null, "FECHA INVALIDA");
  }else{
      String d = Integer.toString(dateText.getCalendar().get(Calendar.DAY_OF_MONTH));
            String mes = Integer.toString(dateText.getCalendar().get(Calendar.MONTH) + 1);
            String y = Integer.toString(dateText.getCalendar().get(Calendar.YEAR));
            m.updatePaciente(id, nameText.getText(), apellidoText.getText(), (int) edadText.getValue(), m.getFecha(d, mes, y),
                    lvlText.getSelectedItem().toString(), religionText.getSelectedItem().toString(), ocupacionText.getText(), actText.getText(), direccionText.getText(), telefonoText.getText(),
                    asuntoText.getText(), objText.getText());
  }
       
    }//GEN-LAST:event_editarActionPerformed

    private void siEmbarazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siEmbarazoActionPerformed
        // TODO add your handling code here:
       embarazoEdad.setEnabled(true);
            noEmbarazo.setSelected(false);
    }//GEN-LAST:event_siEmbarazoActionPerformed

    private void siTraumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siTraumaActionPerformed
        // TODO add your handling code here:
        infoTraumaText.setEnabled(true);
        noTrauma.setSelected(false);
    }//GEN-LAST:event_siTraumaActionPerformed

    private void noTraumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noTraumaActionPerformed
        // TODO add your handling code here:
        infoTraumaText.setEnabled(false);
        siTrauma.setSelected(false);
    }//GEN-LAST:event_noTraumaActionPerformed

    private void VolverProblemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverProblemaActionPerformed
        // TODO add your handling code here:
         m.openPacientes();
        m.closePrincipal();
    }//GEN-LAST:event_VolverProblemaActionPerformed

    private void volverSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverSocialActionPerformed
        // TODO add your handling code here:
         m.openPacientes();
        m.closePrincipal();
    }//GEN-LAST:event_volverSocialActionPerformed

    private void volverSexualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverSexualActionPerformed
        // TODO add your handling code here:
         m.openPacientes();
        m.closePrincipal();
    }//GEN-LAST:event_volverSexualActionPerformed

    private void volverHabitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverHabitoActionPerformed
        // TODO add your handling code here:
         m.openPacientes();
        m.closePrincipal();
    }//GEN-LAST:event_volverHabitoActionPerformed

    private void volverClinicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverClinicoActionPerformed
        // TODO add your handling code here:
         m.openPacientes();
        m.closePrincipal();
    }//GEN-LAST:event_volverClinicoActionPerformed

    private void VolverAntFamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverAntFamActionPerformed
        // TODO add your handling code here:
         m.openPacientes();
        m.closePrincipal();
    }//GEN-LAST:event_VolverAntFamActionPerformed

    private void volverMentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverMentalActionPerformed
        // TODO add your handling code here:
         m.openPacientes();
        m.closePrincipal();
    }//GEN-LAST:event_volverMentalActionPerformed

    private void volverReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverReporteActionPerformed
        // TODO add your handling code here:
         m.openPacientes();
        m.closePrincipal();
    }//GEN-LAST:event_volverReporteActionPerformed

    private void volverFamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverFamActionPerformed
        // TODO add your handling code here:
         m.openPacientes();
        m.closePrincipal();
    }//GEN-LAST:event_volverFamActionPerformed

    private void EditarProblemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarProblemaActionPerformed
        // TODO add your handling code here:
        m.updateProblema(id, evolucionText.getText(), causasText.getText(), accionesText.getText(), implicacionesText.getText());
        
    }//GEN-LAST:event_EditarProblemaActionPerformed

    private void editarSocialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarSocialesActionPerformed
        // TODO add your handling code here:
        m.updateSociales(id, socialText.getText(), laboralText.getText(), viviendaText.getText());
    }//GEN-LAST:event_editarSocialesActionPerformed

    private void noEmbarazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noEmbarazoActionPerformed
        // TODO add your handling code here:
        embarazoEdad.setEnabled(false);
        siEmbarazo.setSelected(false);
    }//GEN-LAST:event_noEmbarazoActionPerformed

    private void editarSexualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarSexualActionPerformed
        // TODO add your handling code here:
        String embarazo="";
        String traumas="";
        if (siEmbarazo.isSelected()) {
            embarazo = "Si";
            if (siTrauma.isSelected()) {
                traumas = "Si";
                m.updateSexual(id, antSexualText.getText(), embarazo, (int) embarazoEdad.getValue(), preferenciaText.getText(), traumas, infoTraumaText.getText());
            } else {
                traumas = "No";
                 m.updateSexual(id, antSexualText.getText(), embarazo, (int) embarazoEdad.getValue(), preferenciaText.getText(), traumas, "");
            }
        } else {
            embarazo = "No";
            if (siTrauma.isSelected()) {
                traumas = "Si";
                 m.updateSexual(id, antSexualText.getText(), embarazo, 0, preferenciaText.getText(), traumas, infoTraumaText.getText());
            } else {
                traumas = "No";
                 m.updateSexual(id, antSexualText.getText(), embarazo, 0, preferenciaText.getText(), traumas, "");
            }
        }
        
    }//GEN-LAST:event_editarSexualActionPerformed

    private void editarHabitosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarHabitosActionPerformed
        // TODO add your handling code here:
        m.updateHabitos(id, dreamText.getText(), alimentoText.getText(), antPsiText.getText());
    }//GEN-LAST:event_editarHabitosActionPerformed

    private void editarClinicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarClinicoActionPerformed
        // TODO add your handling code here:
        m.updateClinicos(id, enfermedadText.getText(), accidenteText.getText(), medicamentoText.getText(), intervencionText.getText(), auxText.getText());
    }//GEN-LAST:event_editarClinicoActionPerformed

    private void editarAntFamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarAntFamActionPerformed
        // TODO add your handling code here:
        m.updateFamiliares(id, antFamPsiText.getText(), antFamPsiqText.getText(), antFamPatText.getText());
    }//GEN-LAST:event_editarAntFamActionPerformed

    private void editarMentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarMentalActionPerformed
        // TODO add your handling code here:
        m.updateMental(id, lenguajeText.getText(), emocionalText.getText(), realidadText.getText(), higieneText.getText());
    }//GEN-LAST:event_editarMentalActionPerformed

    private void editarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarReporteActionPerformed
        // TODO add your handling code here:
        m.updateReporte(id, diagnosticoText.getText(), observacionText.getText());
    }//GEN-LAST:event_editarReporteActionPerformed

    private void famNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_famNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_famNombreActionPerformed

    private void ingresarFamiliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarFamiliarActionPerformed
        // TODO add your handling code here:
        if ( m.insertFamiliar(id, famNombre.getText(),famApellido.getText(), famParentesco.getText(), (int) famEdad.getValue(), famOcupacion.getText())==true) {
       
            showTableData(m.getFamiliaress(id));
        }
       
        
    }//GEN-LAST:event_ingresarFamiliarActionPerformed

    private void familiaTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_familiaTableMouseClicked
        // TODO add your handling code here:
        famID = (int) familiaTable.getValueAt(familiaTable.getSelectedRow(), 0);
    }//GEN-LAST:event_familiaTableMouseClicked

    private void famApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_famApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_famApellidoActionPerformed

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        // TODO add your handling code here:
        if (famID==0) 
        {
             JOptionPane.showMessageDialog(null, "FAVOR DE SELECCIONAR A UN INDIVIDUO!");
        }
        else
        {
            m.deleteFamiliar(famID);
            showTableData(m.getFamiliaress(id));
        }
    }//GEN-LAST:event_borrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditarProblema;
    private javax.swing.JButton VolverAntFam;
    private javax.swing.JButton VolverProblema;
    private javax.swing.JTextArea accidenteText;
    private javax.swing.JTextArea accionesText;
    private javax.swing.JTextField actText;
    private javax.swing.JTextArea alimentoText;
    private javax.swing.JTextArea antFamPatText;
    private javax.swing.JTextArea antFamPsiText;
    private javax.swing.JTextArea antFamPsiqText;
    private javax.swing.JTextArea antPsiText;
    private javax.swing.JTextArea antSexualText;
    private javax.swing.JTextField apellidoText;
    private javax.swing.JTextField asuntoText;
    private javax.swing.JTextArea auxText;
    private javax.swing.JButton borrar;
    private javax.swing.JTextArea causasText;
    private com.toedter.calendar.JDateChooser dateText;
    private javax.swing.JTextArea diagnosticoText;
    private javax.swing.JTextField direccionText;
    private javax.swing.JTextArea dreamText;
    private javax.swing.JSpinner edadText;
    private javax.swing.JButton editar;
    private javax.swing.JButton editarAntFam;
    private javax.swing.JButton editarClinico;
    private javax.swing.JButton editarHabitos;
    private javax.swing.JButton editarMental;
    private javax.swing.JButton editarReporte;
    private javax.swing.JButton editarSexual;
    private javax.swing.JButton editarSociales;
    private javax.swing.JSpinner embarazoEdad;
    private javax.swing.JTextArea emocionalText;
    private javax.swing.JTextArea enfermedadText;
    private javax.swing.JTextArea evolucionText;
    private javax.swing.JTextField famApellido;
    private javax.swing.JSpinner famEdad;
    private javax.swing.JTextField famNombre;
    private javax.swing.JTextField famOcupacion;
    private javax.swing.JTextField famParentesco;
    private javax.swing.JTable familiaTable;
    private javax.swing.JTextField fechaIngreso;
    private javax.swing.JTextArea higieneText;
    private javax.swing.JTextArea implicacionesText;
    private javax.swing.JTextArea infoTraumaText;
    private javax.swing.JButton ingresarFamiliar;
    private javax.swing.JTextArea intervencionText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JScrollPane jScrollPane25;
    private javax.swing.JScrollPane jScrollPane26;
    private javax.swing.JScrollPane jScrollPane27;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea laboralText;
    private javax.swing.JTextArea lenguajeText;
    private javax.swing.JComboBox<String> lvlText;
    private javax.swing.JTextArea medicamentoText;
    private javax.swing.JTextField nameText;
    private javax.swing.JRadioButton noEmbarazo;
    private javax.swing.JRadioButton noTrauma;
    private javax.swing.JTextField objText;
    private javax.swing.JTextArea observacionText;
    private javax.swing.JTextField ocupacionText;
    private javax.swing.JTextField preferenciaText;
    private javax.swing.JTextArea realidadText;
    private javax.swing.JComboBox<String> religionText;
    private javax.swing.JRadioButton siEmbarazo;
    private javax.swing.JRadioButton siTrauma;
    private javax.swing.JTextArea socialText;
    private javax.swing.JTextField telefonoText;
    private javax.swing.JTextArea viviendaText;
    private javax.swing.JButton volver;
    private javax.swing.JButton volverClinico;
    private javax.swing.JButton volverFam;
    private javax.swing.JButton volverHabito;
    private javax.swing.JButton volverMental;
    private javax.swing.JButton volverReporte;
    private javax.swing.JButton volverSexual;
    private javax.swing.JButton volverSocial;
    // End of variables declaration//GEN-END:variables
private motor m;
    private int id;
    private int famID;
}
